platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'VeriffSdk' do
  # Pods for VeriffSdk
  pod 'VeriffSDK'
  pod 'lottie-ios'

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  use_react_native!(
    :path => config[:reactNativePath]
  )
end
